### ISSUE TITLE
Traceback error after viewers have been sent

### ISSUE THREAD

**Issue by ADkilla** [Kichi779/Twitch-Viewer-Bot#34]
This happens every time the cycle is complete.

`Traceback (most recent call last):
  File "C:\Users\11\Downloads\Twitch-Viewer-Bot-main\main.py", line 204, in <module>
    main()
  File "C:\Users\11\Downloads\Twitch-Viewer-Bot-main\main.py", line 198, in main
    set_stream_quality(driver, set_160p)
  File "C:\Users\11\Downloads\Twitch-Viewer-Bot-main\main.py", line 54, in set_stream_quality
    element = driver.find_element(By.XPATH, element_xpath)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\11\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\11\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@data-a-target='player-overlay-click-handler']"}
  (Session info: chrome-headless-shell=126.0.6478.127)`

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
