### ISSUE TITLE
Error when trying run on ubuntu

### ISSUE THREAD

**Issue by Knitted** [Kichi779/Twitch-Viewer-Bot#39]
Hello i have those errors when try to run on ubuntu:

Traceback (most recent call last):
  File "main.py", line 142, in <module>
    main()
  File "main.py", line 124, in main
    driver = webdriver.Chrome(options=chrome_options)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 109, in assert_process_still_running
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

**Comment by Knitted** [comment]
Solved!

**Comment by wizdom-nerd** [comment]
check out this working version: video link: https://www.youtube.com/watch?v=PDu2QQTgCZ4 
discord link: https://discord.gg/Uf5RPA8Vyr
